//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serafim_KURSACH
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> number { get; set; }
    }
}
