//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serafim_KURSACH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
